// @generated by tools/gen_types.py — DO NOT EDIT（db schema 变更后重跑生成器）
// 同步层的领域行类型，与 SQLite 表结构一一对应；由 SYNC_PROTOCOL.md 的表集合定义。

export interface TodoListRow {
  id: string
  display_name: string
  sort_order: number | null
  created_at: string | null
  updated_at: string | null
}

export interface TodoRow {
  id: string
  list_id: string
  title: string
  body: string | null
  status: string | null
  importance: string | null
  due_date: string | null
  planned_date: string | null
  start_date: string | null
  complexity: string | null
  tags: string | null
  created_at: string | null
  completed_at: string | null
  sort_order: number | null
  updated_at: string | null
}

export interface LayerConfigRow {
  layer_id: string | null
  display_name: string
  enabled: number | null
  color: string | null
  sort_order: number | null
  kind: string | null
  group_name: string | null
  config_json: string | null
  updated_at: string | null
}

export interface MetaRow {
  key: string | null
  value: string | null
  updated_at: string | null
}

export interface ScheduleRow {
  date: string | null
  am: string | null
  pm: string | null
  ev: string | null
  updated_at: string | null
}

export interface ColoringRow {
  date: string | null
  level: number
  updated_at: string | null
}

export interface EventRow {
  id: number
  layer_id: string
  source: string
  date: string
  title: string
  description: string | null
  color: string | null
  extra_json: string | null
  source_ref: string | null
  sort_key: number | null
  created_at: string | null
  updated_at: string | null
  sync_uid: string | null
}

export interface ScheduleItemRow {
  id: number
  date: string
  start_time: string | null
  end_time: string | null
  title: string
  color: string | null
  category: string | null
  sort_order: number | null
  created_at: string | null
  updated_at: string | null
  sync_uid: string | null
}

export interface CountdownRow {
  id: number
  name: string
  category: string
  base_date: string
  repeat_yearly: number | null
  repeat_type: string | null
  milestone_rule: string | null
  never_expire: number | null
  notes: string | null
  color: string | null
  sort_order: number | null
  created_at: string | null
  updated_at: string | null
  sync_uid: string | null
}

export interface MarkRow {
  id: number
  layer_id: string
  date: string
  level: number | null
  note: string | null
  created_at: string | null
  updated_at: string | null
  sync_uid: string | null
}

export interface SubscriptionRow {
  id: string
  display_name: string
  source_key: string
  url: string | null
  rules_text: string | null
  enabled: number | null
  auto_update: number | null
  status: string | null
  last_synced_at: string | null
  config_json: string | null
  created_at: string | null
  updated_at: string | null
}

export type TableName =
  | 'todo_list'
  | 'todo'
  | 'layer_config'
  | 'meta'
  | 'schedule'
  | 'coloring'
  | 'events'
  | 'schedule_items'
  | 'countdown'
  | 'marks'
  | 'subscriptions'

export interface Snapshot {
  todo_list?: TodoListRow[]
  todo?: TodoRow[]
  layer_config?: LayerConfigRow[]
  meta?: MetaRow[]
  schedule?: ScheduleRow[]
  coloring?: ColoringRow[]
  events?: EventRow[]
  schedule_items?: ScheduleItemRow[]
  countdown?: CountdownRow[]
  marks?: MarkRow[]
  subscriptions?: SubscriptionRow[]
}

export type RowKey = string
export interface Tombstones { [tablePipeKey: string]: string }
