"""从 SQLite schema 生成 frontend/src/core/types.ts（幂等）。

运行：python tools/gen_types.py
db schema 变更后重跑；生成文件头部带 @generated 标记，禁止手改。
"""

import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tt_calendar import db
from tt_calendar.sync.schema import ensure_sync_schema, SYNC_TABLES

OUT = ROOT / "frontend" / "src" / "core" / "types.ts"

HEADER = """\
// @generated by tools/gen_types.py — DO NOT EDIT（db schema 变更后重跑生成器）
// 同步层的领域行类型，与 SQLite 表结构一一对应；由 SYNC_PROTOCOL.md 的表集合定义。
"""

TS_TYPES = {
    "TEXT": "string",
    "INTEGER": "number",
    "REAL": "number",
    "BLOB": "string | null",
}

PASCAL = {"todo": "TodoRow", "todo_list": "TodoListRow", "layer_config": "LayerConfigRow",
          "meta": "MetaRow", "schedule": "ScheduleRow", "coloring": "ColoringRow",
          "events": "EventRow", "schedule_items": "ScheduleItemRow",
          "countdown": "CountdownRow", "marks": "MarkRow"}


def sql_type_to_ts(decl: str) -> str:
    t = (decl or "TEXT").upper()
    for k, v in TS_TYPES.items():
        if t.startswith(k):
            return v
    return "string"


def main() -> None:
    conn = sqlite3.connect(":memory:", detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    db.init_db(conn)
    ensure_sync_schema(conn)

    lines = [HEADER]
    for table in SYNC_TABLES:
        rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
        fields = []
        for r in rows:
            name = r["name"]
            ts = sql_type_to_ts(r["type"])
            field = ts if r["notnull"] or name == "id" else f"{ts} | null"
            fields.append(f"  {name}: {field}")
        lines.append(f"export interface {PASCAL[table]} {{")
        lines.extend(fields)
        lines.append("}")
        lines.append("")

    lines.append("export type TableName =")
    lines.extend(f"  | '{t}'" for t in SYNC_TABLES)
    lines.append("")
    lines.append("export interface Snapshot {")
    lines.extend(f"  {t}?: {PASCAL[t]}[]" for t in SYNC_TABLES)
    lines.append("}")
    lines.append("")
    lines.append("export type RowKey = string")
    lines.append("export interface Tombstones { [tablePipeKey: string]: string }")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
